hack_it_level_1/config/routes.rb
HackItLevel1::Application.routes.draw do
  root 'static_pages#home'
  
  match '/admin',     to: 'static_pages#admin',     via: 'get'
  match '/converter', to: 'static_pages#converter', via: 'get'
  match '/what',      to: 'static_pages#what',      via: 'get'

  match '/updateField', to: 'static_pages#update_field', via: 'post'

  match '/admin',       to: 'static_pages#update_rate', via: 'post'
end

hack_it_level_1/app/models/info.rb
class Info < ActiveRecord::Base
end

hack_it_level_1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

hack_it_level_1/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
      @info = Info.first;
      if cookies[:user_type].nil?
         cookies[:user_type] = 2;
      end
  end
   
  def admin
      @msg = "";
      @info = Info.first;
  end
  
  def converter
      @rate = Info.first.rate;
      if cookies[:user_type].nil?
         cookies[:user_type] = 2;
      end
  end
   
  def what
  end
   
  def update_field
      hash = {params[:field] => params[:val]};
      Info.first.update_attributes(hash);
      render nothing: true;
  end

  #could get to this by ajax post instead of form ...
  def update_rate
      Info.first.update_attributes(rate: params[:rate][:Rate].to_f);
      @msg = "Success";
      render 'static_pages/admin';
  end
end

hack_it_level_1/app/helpers/application_helper.rb
module ApplicationHelper
end

hack_it_level_1/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

hack_it_level_1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackItLevel1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

hack_it_level_1/app/views/static_pages/admin.html.erb
<div class="pageDiv">

<% if cookies[:user_type].to_i == 1 %>
   <h1>Update Currency Rate</h1>
   
   <%= form_tag do %>
      <%= number_field(:rate, "Rate", {step: 0.01}); %>
      <%= submit_tag("Update"); %>
   <% end %>
   
   <div>
      <%= @msg %>
   </div>
   
   <br><br>
   <%= link_to "Converter", converter_path %>
      
<% else %>
   <h1>Admin Login</h1>
   
   Username: <input type="text"></input>
   Password: <input type="text"></input>
   <button>Login</button>
   <!-- notice this button submits nothing -->
   
   <br><br>
   <h3>You are close...</h3>
   Now you have to fiddle with some things...
   
   <p id="hintBtn1">A hint</p>
   <div id="hint1" style="display:none;">
      <i>
         731163211911111710810032981013211711510110211710832116111321001
         1111911010811197100329732671041141111091013210112011610
         1110115105111110329997108108101100326910010511684104105
         11567111111107105101324011111432115111109101116104105
         11010332115105109105108971144146
      </i>
   </div>
   <script>
      $("#hintBtn1").on("click", function(){
         $("#hint1").toggle();
      });
   </script>
   
   <p id="hintBtn2">A big hint</p>
   <div id="hint2" style="display:none;">
      <i>
         char c = (char) x;
      </i>
   </div>
   <script>
      $("#hintBtn2").on("click", function(){
         $("#hint2").toggle();
      });
   </script>   
   
<% end %>

</div>

hack_it_level_1/app/views/static_pages/converter.html.erb
<div class="pageDiv">

   <h1>AUD <-> USD Currency Converter</h1>
      <%= link_to "Home", root_path %>
   <br><br><br>
   
<div style="text-align:left">
   <b>Input AUD and hit enter</b>
   <br>

   
   <input type="number" id="aud" step="0.1"></input>
   <button id="btn">Go!</button>
   <br><br>
   
   <b>USD:</b>
   <div id="answer">
   </div>
   
   <p id="hintBtn1">A hint</p>
   <div id="hint1" style="display:none;">
      <i>Hmm, the administrator of the site could really help here...</i>
   </div>
   <script>
      $("#hintBtn1").on("click", function(){
         $("#hint1").toggle();
      });
   </script>
   
   <p id="hintBtn2">A big hint</p>
   <div id="hint2" style="display:none;">
      <i>I bet the administrator has some sort of login which they use to 
      edit the site.</i>
   </div>
   <script>
      $("#hintBtn2").on("click", function(){
         $("#hint2").toggle();
      });
   </script>
   
   <script>
      $("#btn").on("click", function(){
         var aud = $("#aud").val()
         var a = aud * <%= @rate %>;
         $("#answer").text(a.toString());
      });
   </script>
</div>

hack_it_level_1/app/views/static_pages/home.html.erb
<div class="pageDiv">

   <h1>Public Notice Board and Info Site</h1>

   <p style="text-align:left">
      Welcome, this site hosts some generally useful information.
      Anyone is able to post something in the paragraph bellow 
      and it will be seen by anyone who accesses the page.<br><br>
      
      We are also installing a bunch of useful services such as 
      currency exchange calculators. See our links below.
   </p>

   <%= link_to 'AUD-USD Converter', converter_path %>
   &nbsp; &nbsp; &nbsp;
   <%= link_to 'What the?', what_path %>
   
   <hr>
   <div class="noticeBoard">
      <h3 id="title"><%= @info.title %></h3>
      <div id="notice" style="width:400px; height:200px; text-align:left;">
         <%= simple_format(@info.notice); %>
      </div>

      <hr>
      <b>New Notice</b><br>
      <textarea id="newNotice" style="width:400px; height:100px;"></textarea><br>
      <button id="btn">Update</button>
   </div>

   <script>
     
      $("#btn").on("click", function(){
         var str = $("#newNotice").val();
         
         $.ajax({
            
            type: "POST",
            url:  "/updateField",
            data: {field: "notice", val: str}
            
         }).done(function(){
            location.reload();
         });
         
      });
   </script>

</div>

hack_it_level_1/app/views/static_pages/what.html.erb
<div class="pageDiv">

   <h1>HackIt - Level 1</h1>
   <%= link_to "Home", root_path %>
   <br><br><br>

<div style="text-align:left">
This is a very small Rails app designed to be hacked for fun.
<br><br>
<b>There are 2 tasks:</b>
<br>
1. Change the title of the notice board.<br>
2. Change the currency conversion rate.<br>
<br><br>
The code is in <%= link_to "this", "https://github.com/julianborrey/hackItLevel1" %> repo, 
so if you really want a hint you can look at it 
... but might as well have some fun and try do it first with out looking. ;)
<br><br>
Some hints are in the website anyway.
<br><br>
A good rule of advice is to consider all the resources the website sends to you and what resources the website might be using.
<br><br>
Also - to just save you some time, there is no XSS or sanitation breaking in this round.
Probably in level 2 though.
<br><br>
Have fun!
</div>

</div>